### ISSUE TITLE
Feedback on initial draft

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-pixeltracker#1]
* wrong repo name (should be `leadconduit-integration-pixel-tracker`, like all the others)
* doesn’t `npm install` and `cake test` after initial clone (missing dependency on `valid-url`)
* you said, and [the issue says](https://github.com/activeprospect/leadconduit-integrations/issues/20), that it accepts 200, but this accepts 200-299
* header set to accept JSON, but pixels are images. could probably just use `*/*`
* request param should be just `url`, not `lead.url`, as this will always be a mapped value, never data on the lead
* response params misnamed (`email.outcome` & `email.reason`)
* shouldn’t set a `reason` value on “success”
* don’t think the exported name is accurate (not much data being appended here)
* description of `reason` is wrong

**Comment by ros3bud** [comment]
Upon further discussion of this we decided that 2XX should be acceptable.

**Comment by ros3bud** [comment]
@cgrayson, took your suggestions into account and updated this. Any further feedback?

**Comment by cgrayson** [comment]
Good changes. Just a few things: 

1. no need for `name: 'outbound'` in `module.exports`. we only need `name` if the filename (e.g., "outbound") isn't what should show up in the dropdown for the recipient in the flow configuration UI
2. since `valid-url` is used in the module itself (and not just the tests), it needs to be in `package.json`'s `dependencies`, not `devDependencies` 
3. since `url` is only used once in `request()`, could do away with that local variable

Almost there. :+1: Let's go ahead & have PRs from here on out.
