### ISSUE TITLE
needs "logo" image

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-pixeltracker#4]
Noticed there's an entry for this in the API `standard.json` seed file with https://s3.amazonaws.com/integration-logos/pixeltracker.png, but there's no such file uploaded to S3 yet. Not sure what logo makes sense for a non-branded integration like this, but we'll need something.

**Comment by justinwinslow** [comment]
If it doesn't have a logo image it will just display text. This isn't a terrible outcome in my opinion. If someone wants to come up with a logo for "pixeltracker" though, that's also cool. cc @kellym @lookitsbeau @alexj

**Comment by alexkwolfe** [comment]
Just to be clear, either the `logo_url` should point to a valid image file or it should be set to `null`. https://activeprospect.slack.com/archives/leadconduit/p1434654552003539

**Comment by ros3bud** [comment]
updated to null in PR #122
