### ISSUE TITLE
Success response in LCN?

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-pixeltracker#5]
Should a success response from the URL indicate a success response for the pixel tracker?

The example below indicates a success response, yet the outcome is error in the Pixeltracker LCN step.

Thoughts? Should success and 200 indicate a successful step?

Success example:
https://next.leadconduit.com/events/559d4e1c9f49d579041354e9?event_id=559d4e1c9f49d579041354ea

200 example:
https://next.leadconduit.com/events/559d4d0ed765557f046428a6?event_id=559d4d0ed765557f046428a7

**Comment by alexkwolfe** [comment]
@ros3bud, mind looking at this?

**Comment by ros3bud** [comment]
Sure, on it.

**Comment by ros3bud** [comment]
This does seem to be a bug. Thanks for pointing that out @kcaponeAP!

**Comment by ros3bud** [comment]
Fixed in version 0.0.6
