### ISSUE TITLE
Add AP branded logo to Pixel Tracker 

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-pixeltracker#7]
Add AP branded logo to Pixel Tracker for both the menu and the step in LCN. 

@alexj can give more details / timeline

adding @lookitsbeau for creation of logo

**Comment by lookitsbeau** [comment]
Let me know if this works. 

![pixel-tracker](https://cloud.githubusercontent.com/assets/1291126/8655374/559b896a-2956-11e5-9132-286d62c4f471.png)

**Comment by cgrayson** [comment]
This was in place on S3, but needed to be listed in the API entity seed file.
