### ISSUE TITLE
Pixeltracker has lost its icon @ docs.leadconduit.com

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-pixeltracker#8]
Notice how there is no icon or name for the integration in the middle? Please fix.

![screen shot 2015-09-17 at 4 19 30 pm](https://cloud.githubusercontent.com/assets/8238417/9946285/e9b6080c-5d57-11e5-97da-6d7726420758.png)

**Comment by cgrayson** [comment]
It's never gotten a logo yet: #7.

**Comment by cgrayson** [comment]
My mistake, this was actually kind of out there, even though it wasn't showing in the app itself. 

But it was, and still is, visible in the list on `docs.leadconduit.com`. @jgrayson676 said he ran into the same thing recently, and found that a content-blocking browser plugin was to blame. It seems that it didn't like loading an image named "pixeltracker.png". Could that be why you don't see it, @kcaponeAP?

**Comment by kcaponeAP** [comment]
That could be it. I have adblock running always. Reloaded and it appears. The rest of the logos appear with adblock running. Thanks for the heads up.
